apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: example/environment-config
  name: environment-config
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|example|environment-config'
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: "/tmp/.ssh/publickey"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-api-config
  namespace: example
data:
  TRANSACTIONS_API_ADDR: "ledgerwriter:8080"
  BALANCES_API_ADDR: "balancereader:8080"
  HISTORY_API_ADDR: "transactionhistory:8080"
  CONTACTS_API_ADDR: "contacts:8080"
  USERSERVICE_API_ADDR: "userservice:8080"
  # [END gke_boa_kubernetes_manifests_config_configmap_service_api_config]
# [END gke_boa_kubernetes_manifests_config_configmap_service_api_config]
---
# [START gke_boa_kubernetes_manifests_config_configmap_demo_data_config]
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-data-config
  namespace: example
data:
  USE_DEMO_DATA: "True"
  DEMO_LOGIN_USERNAME: "testuser"
  # All demo user accounts are hardcoded to use the login password 'bankofanthos'
  DEMO_LOGIN_PASSWORD: "bankofanthos"
  # [END gke_boa_kubernetes_manifests_config_configmap_demo_data_config]