apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
  namespace: accounts-db-dev
  labels:
    app: accounts-db
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: /tmp/.ssh/publickey
