apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-data-config
  namespace: accounts-db-dev
  labels:
    app: accounts-db
data:
  USE_DEMO_DATA: "True"
  DEMO_LOGIN_USERNAME: testuser
  # All demo user accounts are hardcoded to use the login password 'bankofanthos'
  DEMO_LOGIN_PASSWORD: bankofanthos
