apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: enable-https
  annotations:
    config.kubernetes.io/local-config: "true"
source: |-
  def enable_https(resources):
    hostname = ""
    for resource in resources:
      if resource["kind"] == "Ingress" and resource["metadata"]["name"] == "ghost-app":
        hostname = resource["spec"]["rules"][0]["host"]
        resource["metadata"]["annotations"]["cert-manager.io/cluster-issuer"] = "letsencrypt-prod"
        resource["spec"]["tls"] = [ {"hosts": [hostname], "secretName": hostname + "-tls"}]
        return

  enable_https(ctx.resource_list["items"])
