apiVersion: v1
kind: Service
metadata:
  name: base-app
  namespace: example
  labels:
    app: base-app
spec:
  type: LoadBalancer
  selector:
    app: base-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
