apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: example
  labels:
    app.kubernetes.io/name: backstage
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backstage
          image: gcr.io/kpt-dev/kpt-backstage-plugins/backstage-plugin-cad:v0.1.0
          ports:
            - name: http
              containerPort: 7007
          env:
            - name: AUTH_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cad-google-oauth-client
                  key: client-id
                  optional: false
            - name: AUTH_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cad-google-oauth-client
                  key: client-secret
                  optional: false
    metadata:
      labels:
        app.kubernetes.io/name: backstage
  selector:
    matchLabels:
      app.kubernetes.io/name: backstage
