apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cad-google-oauth-client
  namespace: example
  labels:
    app.kubernetes.io/name: backstage
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-provider # name of the SecretStore (or kind specified)
  target:
    name: cad-google-oauth-client # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: cad-ui-openid-credentials # name of the GCPSM secret key
      version: "1"
