apiVersion: v1
kind: ConfigMap
metadata:
  name: service-api-config
  namespace: example
  labels:
    app: ledgerwriter
data:
  TRANSACTIONS_API_ADDR: ledgerwriter:8080
  BALANCES_API_ADDR: balancereader:8080
  HISTORY_API_ADDR: transactionhistory:8080
  CONTACTS_API_ADDR: contacts:8080
  USERSERVICE_API_ADDR: userservice:8080
