apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb
  namespace: example
  labels:
    app.kubernetes.io/name: mariadb
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-provider # name of the SecretStore (or kind specified)
  target:
    name: mariadb # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: blog-db-credentials # name of the GCPSM secret key
      version: "1"
