# Source: ghost/charts/mariadb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb
  namespace: example
  labels:
    app.kubernetes.io/name: mariadb
automountServiceAccountToken: false
