apiVersion: fn.kpt.dev/v1alpha1
kind: SetImage
metadata:
  name: set-image
  annotations:
    config.kubernetes.io/local-config: "true"
  labels:
    app: base-db
image:
  name: gcr.io/bank-of-anthos-ci/base-db
  newName: gcr.io/bank-of-anthos-ci/base-db
  newTag: db-version
