apiVersion: v1
kind: Service
metadata:
  name: base-db
  labels:
    tier: db
    app: base-db
  namespace: example
spec:
  ports:
    - port: 5432
      name: tcp
      targetPort: 5432
      protocol: TCP
  selector:
    tier: db
    app: base-db
